darwin: Set home dir for prometheus exporter
```
error: config contains the wrong home directory for
_prometheus-node-exporter, aborting activation

nix-darwin does not support changing the home directory of existing users.
```